CREATE TABLE rollcall (
  uid           UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ident         varchar(255) NOT NULL,
  -- item_id       UUID NOT NULL,
  -- result        INTEGER NOT NULL,
  created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at    TIMESTAMP WITHOUT TIME ZONE
);
